In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Numpy merupakan library python digunakan untuk komputasi matriks.
Matplotlib merupakan library puthone untuk presentasi data berupa grafik atau plot

In [2]:
dataset = pd.read_csv('data ikan.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1 ].values

In [3]:
print(x)

[[1 'Belanak' 251.5 38.5 289.8 nan nan]
 [2 'Kakap' 219.6 0.0 219.6 nan nan]
 [3 'Sebelah' 71.5 119.5 191.3 nan nan]
 [4 'Pari' 0.0 0.0 4.5 nan nan]
 [5 'Gulamah' 835.2 151.8 987.0 nan nan]
 [6 'Bawal Hitam ' nan 0.0 nan nan nan]
 [7 'Golok/Parang' 0.0 nan nan nan nan]
 [8 'Ikan Lainnya' 341.7 0.0 341.7 nan nan]
 [9 'Udang Windu ' 0.0 541.3 541.3 nan nan]
 [10 'Udang Putih ' 113.5 860.5 974.0 nan nan]
 [11 'Cumi-Cumi' 0.0 0.0 0.0 nan nan]
 [12 'Kepiting ' 248.5 0.0 248.5 nan nan]]


In [4]:
print(y)

[nan nan nan nan nan nan nan nan nan nan nan nan]


In [11]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 2:3])
x[:, 2:3] = imputer.transform(x[:, 2:3])

In [12]:
print(x)

[[1 'Belanak' 251.5 38.5 289.8 nan nan]
 [2 'Kakap' 219.6 0.0 219.6 nan nan]
 [3 'Sebelah' 71.5 119.5 191.3 nan nan]
 [4 'Pari' 0.0 0.0 4.5 nan nan]
 [5 'Gulamah' 835.2 151.8 987.0 nan nan]
 [6 'Bawal Hitam ' 113.5 0.0 nan nan nan]
 [7 'Golok/Parang' 0.0 nan nan nan nan]
 [8 'Ikan Lainnya' 341.7 0.0 341.7 nan nan]
 [9 'Udang Windu ' 0.0 541.3 541.3 nan nan]
 [10 'Udang Putih ' 113.5 860.5 974.0 nan nan]
 [11 'Cumi-Cumi' 0.0 0.0 0.0 nan nan]
 [12 'Kepiting ' 248.5 0.0 248.5 nan nan]]


In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0 ])], remainder='passthrough')
x =np.array(ct.fit_transform(x))

In [14]:
print(x) 

[[1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 'Belanak' 251.5 38.5
  289.8 nan nan]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 'Kakap' 219.6 0.0 219.6
  nan nan]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 'Sebelah' 71.5 119.5
  191.3 nan nan]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 'Pari' 0.0 0.0 4.5 nan
  nan]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 'Gulamah' 835.2 151.8
  987.0 nan nan]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 'Bawal Hitam ' 113.5
  0.0 nan nan nan]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 'Golok/Parang' 0.0 nan
  nan nan nan]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 'Ikan Lainnya' 341.7
  0.0 341.7 nan nan]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 'Udang Windu ' 0.0
  541.3 541.3 nan nan]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 'Udang Putih ' 113.5
  860.5 974.0 nan nan]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 'Cumi-Cumi' 0.0 0.0 0.0
  nan nan]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0

In [15]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y= le.fit_transform(y)

In [16]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0]


In [17]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1) 

In [18]:
print(x_train)

[[0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 'Cumi-Cumi' 0.0 0.0 0.0
  nan nan]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 'Kakap' 219.6 0.0 219.6
  nan nan]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 'Golok/Parang' 0.0 nan
  nan nan nan]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 'Belanak' 251.5 38.5
  289.8 nan nan]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 'Ikan Lainnya' 341.7
  0.0 341.7 nan nan]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 'Kepiting ' 248.5 0.0
  248.5 nan nan]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 'Udang Putih ' 113.5
  860.5 974.0 nan nan]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 'Udang Windu ' 0.0
  541.3 541.3 nan nan]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 'Bawal Hitam ' 113.5
  0.0 nan nan nan]]


In [19]:
print(x_test)

[[0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 'Sebelah' 71.5 119.5
  191.3 nan nan]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 'Pari' 0.0 0.0 4.5 nan
  nan]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 'Gulamah' 835.2 151.8
  987.0 nan nan]]


In [20]:
print(y_train)

[0 0 0 0 0 0 0 0 0]


In [21]:
print(y_test)

[0 0 0]
